### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by Callial** [freddedotme/BuildSubmission#2]
It seems like this would be a great plugin and I would love to use it on my server, however, you don't have any documentation on how to actually use it i.e. Setup ranks, Setup rank permissions, is there a way to add rank names rather than numbers? is there a way to have a prefix or suffix in chat or tab?. If you could please go into more depth on these that would be great 😄. 
~Callial

**Comment by freddedotme** [comment]
Most of the information can be found here: http://fredde.me/BuildSubmission/
Is there something specific you couldn't find?
