### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Callial** [freddedotme/BuildSubmission#5]
Ok, I am finally ready to set up the configuration for this plugin and I just have a few questions about the structure setup of the files.

- I assume in the commands.yml I need both an online and an offline command for every rank if I want the player to see a message that is.

- In the setup of these commands if I am using PEX can the {rank1} be the rank name or is it for BS only so it can assign a numerical value to the rank?.

- Does resetting a player's rank reset just the number BS assigns to ranks(If my second assumption is correct) or does it reset any PEX rank as well?

I think these are all the questions I have but if your answers bring up more please give me at least two days to respond as I am fairly busy both helping in the development of the server and participating in real life events.

**Comment by freddedotme** [comment]
1. The minimum is to have at least one of them. It depends on your scenario, if it's something that requires the player to be online, like teleporting him/her then you'd need an online command. The reason of the offline command is for example if you approve a build when the player is offline. As of now the plugin only execute the commands when an approval happens.

2.  The {rank1} is relating to the rank in the builders.yml, therefore it has to be a number that is between your interval of ranks. If you're rank 2 and a moderator approves your build it looks for the next rank command which would be {rank3}.

3. The reset command resets the value of that player in the builders.yml, correct (might be a feature to include commands to run on a reset?).

Hope that helps.

**Comment by Callial** [comment]
1. That cleared that question up thanks :)
2. Do I have to do any manual editing of the builders.yml or is it just a compilation of users? Also in the offline examples you showed {} around the player tag but in the pex example you showed me in an earlier issue you used <> Which do I use?
3. I would love being able to customize what command runs on the reset.

As I am almost done setting up I should be able to get some more details soon about how it is working, so please leave this thread open for at least two more days and I will post here if all goes well.

Also is there a command to just reload this plugin? it is rather annoying to just change a few words in a text file and have to restart the server afterward.

Edit: I have encountered an issue, after editing the commands.yml in the format you showed me in a previous issue, and trying both <player> and {player}, and now any bs command does nothing but bring up the bs help message

**Comment by freddedotme** [comment]
2. builders.yml is a flat file database in a sense, no need to manually edit it, the plugin writes/read to/from it. Use '{}' in commands.yml.
3. Will be added when I have time.

Good luck.

**Comment by freddedotme** [comment]
Please use the "insert code" icon above where you comment and paste your commands.yml file.

**Comment by Callial** [comment]
```
ONLINE:
- '{rank1} tell {player} You have started on your journey of becoming of societies elite congrats.'
- '{rank2} tell {player} Congratz'
- '{rank3} tell {player} Congratz'
- '{rank4} tell {player} Congratz'
- '{rank5} tell {player} you now hold a prestigous place among your fellow Orbians you can own property in town.'
- '{rank6} tell {player} Congratz'
- '{rank7} tell {player} Congratz'
- '{rank8} tell {player} Congratz'
- '{rank9} tell {player} Congratz'
- '{rank10} tell {player} Through effort and determination you are now ranked among the best, Orbians idolise you.'
OFFLINE:
- '{rank1} pex promote {player} bs'
- '{rank2} pex promote {player} bs'
- '{rank3} pex promote {player} bs'
- '{rank4} pex promote {player} bs'
- '{rank5} pex promote {player} bs'
- '{rank6} pex promote {player} bs'
- '{rank7} pex promote {player} bs'
- '{rank8} pex promote {player} bs'
- '{rank9} pex promote {player} bs'
- '{rank10} pex promote {player} bs'
```

**Comment by freddedotme** [comment]
Hm, can't find any typos or invalid formatting. Do you get any kind of errors or output in your server log?

**Comment by Callial** [comment]
Sorry for the delay, was on vacation 

### **builders.yml**

```
    50ba0766-73f5-4e2b-9acc-fd87c979bf4d:
      rank: 0
    29a7d8df-8069-4089-ab0f-35606f7b933c:
      rank: 0
    2461ca25-32e0-49e1-998a-df920422dbd0:
      rank: 0
    cd98ef60-03ff-45ce-834b-19fb750a816a:
      rank: 0
    bd1a4810-1d9d-4a22-875b-a897dd3ebd38:
      rank: 0
    c64b3728-b18b-4e9e-b9d0-8c399f7e3a58:
      rank: 0
    adf9cb5f-23dd-4d13-bcea-7d56c9f579a1:
      rank: 0
    945e2c33-eea9-4e2d-85d8-e0d6488f5d9a:
      rank: 0
    2c94741d-015d-4078-aefd-dc6d2b6d865e:
      rank: 0
```

### **commands.yml**

```
    ONLINE:
    - '{rank1} tell {player} You have started on your journey of becoming one of societies elite, congrats.'
    - '{rank2} tell {player} Congratz'
    - '{rank3} tell {player} Congratz'
    - '{rank4} tell {player} Congratz'
    - '{rank5} tell {player} you now hold a prestigous place among your fellow Orbians and you can own property in town.'
    - '{rank6} tell {player} Congratz'
    - '{rank7} tell {player} Congratz'
    - '{rank8} tell {player} Congratz'
    - '{rank9} tell {player} Congratz'
    - '{rank10} tell {player} Through effort and determination you are now ranked among the best, Orbians idolise you.'
    OFFLINE:
    - '{rank1} pex promote {player} bs'
    - '{rank2} pex promote {player} bs'
    - '{rank3} pex promote {player} bs'
    - '{rank4} pex promote {player} bs'
    - '{rank5} pex promote {player} bs'
    - '{rank6} pex promote {player} bs'
    - '{rank7} pex promote {player} bs'
    - '{rank8} pex promote {player} bs'
    - '{rank9} pex promote {player} bs'
    - '{rank10} pex promote {player} bs'
```

### **chat.yml**

```
    SUBMITTED: '&eBuild submitted.'
    APPROVED: '&aCongrats, your build was approved!'
    DENIED: '&cSorry, your build got denied.'
    INVALID: '&cInvalid argument or command.'
    CANCEL: '&eYour submission has been cancelled.'
```
These are all of the documents
I also took the time to look through logs and all that happens when I type any of the commands is it just repeats the command in the log with no error.

**Comment by freddedotme** [comment]
If I understand it correctly it just spits out the command you write in the log? So for example if you write "/build submit" it just spits that out again in the log?

The files looks like they should but I wonder if you have setup the permissions to actually use the commands? Check the main page and you see what they are.

Try that and if it doesn't work it would be good if I could visit your server and we'll try to debug it together.

Also for future reference, could you just attach version of BS and Java.

Cheers.

**Comment by Flar3on12** [comment]
Hello there,
I am Flar3 I'm taking over this project from dragon, would you be so kind as to fill me in on where he was at? I am fairly new to this so If you could point me in the right direction I can Finish the project and learn the appropriate skills to finish this.
thanks a million!
~flar3

**Comment by freddedotme** [comment]
Hi there,
Alright, well just check the messages above my last one and you see where the issue is.

**Comment by Flar3on12** [comment]
brilliant thank you sir. :)

**Comment by Callial** [comment]
Hai again XD,
I have successfully got everything working and I would just like to make a few suggestions :)

1. Can you add to the commands file a command that is run when you reset a players rank.
2. Can you add a way to save previous builds that have been submitted, or add plotsquared support so it submits a whole plot.
3. Can you add a way to set a max rank besides just adding the command to tell a player they have reached a max rank, as the rank number would still increase.
4. Is there a way to run multiple commands per rank? if not could you add one

Once you have responded to these go ahead and close this issue and if I find anything else I will just start a new one.

**Comment by freddedotme** [comment]
1. Sure, when I have time.
2. Same answer as 1.
3. Hmm, should work already but I can double check it.
4. You can already do this, just add a new line for a new command. I think there are examples over at the front page.

**Comment by Callial** [comment]
Thanks :)
and yeah with number 3 it ranks up past the last rank in the command file the only difference is that the rank number changes
